language: node_js
sudo: false
node_js: stable
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
cache:
  directories:
  - node_modules
before_script:
  - npm install -g polymer-cli  
install:
  - npm install
script:
  - npm run pretest
  - xvfb-run wct --npm
dist: trusty
